### PR TITLE
Remove author information from extended models

### PR DESCRIPTION
**Pull request by harmenjanssen**
It's a fun feature but creates a git dependency that we can do without.

### CODE REVIEW

**Comment by harmenjanssen** [comment]
Yeah, why the hell not? It contains useless information now anyway. Less is more.

**Comment by harmenjanssen** [comment]
I have also removed the useless `public function init() { parent::init(); }`, agreed?

**Comment by martijngastkemper** [comment]
The `phpcs.xml` must be changed as well. You will get a warning: the class docblock is missing. And that needs to be added to the changelog. Then it's complete I think.

**Comment by harmenjanssen** [comment]
Like this?

**Comment by martijngastkemper** [comment]
Yes. Tested it and LGTM!

**Pull request merged**
