### PR TITLE
Minimum stability in Composer

### PR DESCRIPTION
**Pull request by schoenkaft**
- Locked phpdotenv
- Changed stablity to stable
- Made zendframework1 version a bit more specific
- Moved faker to require-dev and imported the dev version, since master is way out of sync, and we use some of those classes
- Added PHP to dependencies

### CODE REVIEW

**Comment by schoenkaft** [comment]
Falende test, deze class + functie bestaat niet in `1.6.0`, maar wel in `master`: https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/HtmlLorem.php

Zie ook: https://github.com/fzaninotto/Faker/issues/1150

**Comment by harmenjanssen** [comment]
Why the specific Zend Framework version?

**Comment by schoenkaft** [comment]
Because I think `"zendframework/zendframework1": "^1.12.20"` is more informative, verbose and safe than `"zendframework/zendframework1": "^1.*"`.

**Comment by harmenjanssen** [comment]
Sure. Although I'm prepared to eat every upcoming ZF 1.* version that's going to be released.

I'm going to merge this.

**Comment by schoenkaft** [comment]
Well, that's exactly what this does right? Every version from `1.12.20` upwards will be used. In theory you could actually go downwards with `1.*`. But we're bikeshedding... ;)

**Pull request merged**
